fix: trigger action strings for trigger_type and flow_type
zitadel/terraform-provider-zitadel pull request #68
Opened 2023-03-20 15:44 UTC by stebenz

2023-03-20 16:19 UTC, eliobischof requested changes

2023-03-20 16:19 UTC, eliobischof commented on zitadel/v2/trigger_actions/resource.go
> +		0: "TRIGGER_TYPE_UNSPECIFIED",
Let's remove TRIGGER_TYPE_UNSPECIFIED

2023-03-20 16:19 UTC, eliobischof commented on zitadel/v2/trigger_actions/resource.go
> +		0: "FLOW_TYPE_UNSPECIFIED",
Let's remove FLOW_TYPE_UNSPECIFIED

2023-03-22 13:19 UTC, stebenz commented on zitadel/v2/trigger_actions/resource.go
> +		0: "TRIGGER_TYPE_UNSPECIFIED",
Agreed.

2023-03-22 13:19 UTC, stebenz commented on zitadel/v2/trigger_actions/resource.go
> +		0: "FLOW_TYPE_UNSPECIFIED",
Agreed.

2023-03-22 21:28 UTC, eliobischof approved these changes

2023-03-23 14:42 UTC, merged