docs: bug report issue template
zitadel/terraform-provider-zitadel pull request #86
Opened 2023-04-28 11:44 UTC by hifabienne

2023-04-28 13:34 UTC, eliobischof reviewed
Let's require a user story in all the templates? As <role>, I want...

2023-04-28 13:34 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/bug_report.yaml
Also interesting is the target environment:
- ZITADEL Cloud
- Self Hosted ZITADEL Version

2023-04-28 13:34 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/improvement
add .yaml file ending

2023-04-28 13:34 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/improvement
> +labels: ["type: improvement"]
```suggestion
labels: ["improvement"]
```

2023-04-28 13:34 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/improvement
How does it differ from Proposal / Feature Request?

2023-04-28 14:29 UTC, hifabienne commented on .github/ISSUE_TEMPLATE/improvement
For me a feature request is something new. and an improvement is something we already have but should change in a way but is not a bug.

example: 
- Feature Request: Adding groups possibilty
- Improvement: The redirect urls of apps should be added the same way as servers on ldaps. 

Not sure if we really need both. I just had the feeling that customers sometimes don't know where to add.

2023-04-28 15:15 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/improvement
Having more choices makes the decision harder, doesn't it? 😄

What about adding " / Improvements" to the other template?

2023-05-01 06:13 UTC, hifabienne commented on .github/ISSUE_TEMPLATE/improvement
A feature is something new and a improvement something existing that should be changed

2023-05-19 14:03 UTC, hifabienne commented on .github/ISSUE_TEMPLATE/bug_report.yaml
The terraform provider, you can't setup instances with the provider in our cloud.

2023-05-22 08:35 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/improvement
@stebenz do you think we should have a "Proposal / Feature request" issue template as well as an "Improvement" template?

2023-05-24 14:05 UTC, eliobischof requested changes

2023-05-24 14:05 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/bug_report.yaml
Let's add a required "impact" textarea field?
Something like
*"Describe your problems caused by this bug"*

2023-05-24 14:05 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/proposal.yaml
> +      description: Is your proposal / feature request related to a problem. Please describe it.
We don't care if it doesn't solve a real problem, right?
```suggestion
      description: Please describe your problem this proposal / feature is supposed to solve.
```

2023-05-25 06:10 UTC, hifabienne commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +    description: Which version of the Terrafor Provider are you using.
I changed the description field to impact, and changed the description to your suggestion.

2023-05-25 06:18 UTC, eliobischof commented on .github/ISSUE_TEMPLATE/bug_report.yaml
I see you replaced the description field :+1:

2023-05-25 06:20 UTC, eliobischof approved these changes

2023-05-25 07:27 UTC, merged